name: Test
on: push

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    # see https://github.com/actions/checkout/issues/760
    - name: adding github workspace as safe directory
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
