name: Test
on: push

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    # see https://github.com/actions/checkout/issues/760
    - name: git-workaround
      run: |
        export REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        git config --global --add safe.directory /__w/${REPOSITORY_NAME}/${REPOSITORY_NAME}

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
